name: Docker image deploy
on:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: get metadata
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         image: ghcr.io/masebb/docker-dnsmasq
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        provenance: false
        push: true
        tags: |
          ghcr.io/masebb/docker-dnsmasq:${{ github.ref_name }}
          ghcr.io/masebb/docker-dnsmasq:latest